### ISSUE TITLE
Missing bug/model

### ISSUE THREAD

**Issue by vaibhav-kaushal** [goradd/goradd#165]
I am starting off with goradd and followed the [Quick Start guide](https://github.com/vaibhav-kaushal/goradd/blob/master/doc/quickstart.md)

I have a import statement in `web/login/login_form.go` for `"goradd-project/gen/bug/model"` which is unresolved. How do I fix it? 

I was using `dep` with go 1.12 the last time I made an app with golang and am new to the go modules. How do I resolve this?

**Comment by spekary** [comment]
Thank you for reporting this. It should be fixed now. You can do one of the following:

1) Delete these two directories:
  a) goradd-project/auth
  b) goradd-project/web/login

or

2) Start over, and download and run the install again.

**Comment by vaibhav-kaushal** [comment]
Sure. I will start over. Maybe after an hour.
