### ISSUE TITLE
Incomplete SQL for Creating the MySQL Database

### ISSUE THREAD

**Issue by vaibhav-kaushal** [goradd/goradd#170]
Hello @spekary I think the SQL dump shown by the "Configure the database" page in the tutorial has incomplete SQL for creating the DB and the reason is that the statements for making the indexes and foreign keys are commented out in the SQL. I think you have used phpMyAdmin for exporting and for some reason it chose not to enable the indexes and foreign keys (actually, even primary keys) in that export. 

I think you might have to enable that.

**Comment by spekary** [comment]
Its not that, but it is a bug. Its a problem with word wrap.

**Comment by spekary** [comment]
Fixed in #172. Run `go get -u ...` to get latest.
