### ISSUE TITLE
Sample templates

### ISSUE THREAD

**Issue by vaibhav-kaushal** [goradd/goradd#171]
I have created the goradd project and wanted to run the codegen but I see no templates in the `tmp/templates` folder. Where can I get some sample templates to run from? @spekary Do you have some of them? I would love to try something with goradd. 

PS: @spekary Can we change the name? _goradd_ sounds dry and I have to explain to them that it is not _gored_, _gorad_ or _goredd_ when mentioning it.

**Comment by vaibhav-kaushal** [comment]
OK, I was running the command in the wrong directory and was hoping for a miracle. I am a fool!!

**Comment by spekary** [comment]
Heh. goradd stands for Go Rapid Application Development and Deployment. But if you have another suggestion, I am open.

To run codegen, you currently would do `go generate` on the groadd-project/codegen/cmd directory. 

The codegen process will create forms, controls and the orm. The forms will have matching templates, and you can see them at goradd-project/gen/{dbname}/form and goradd-project/gen/{dbname}/panel. Look for the files that end in .tpl.got. Running `go generate` turns these files into .tpl.go files that will get compiled into the application.

The files in tmp are intermediate files used by the codegen process. Essentially, codegen uses templates found in goradd-src (which is on your computer in go's package cache, but you can see this in goradd's github too.) The templates are at codegen/templates/*. These templates are run through GoT to create GO files that are place in the tmp directory, and these intermediate files are then combined with codegen.go to create an app that then generates the files found in goradd-project/gen/*. The reason for these intermediate templates is that you can override individual templates in the code generation process by placing templates in goradd-project/codegen/templates, similar to how it is done in qcubed. Each file there will override the default found in goradd-src. So, customizing the codegen process is possible, but it requires reading through the goradd-src/ codgen/templates to understand how they create the various generated files. The process is complicated to describe, but overriding the individual template files is actuall pretty straight forward. You just name it the same as the file you are overriding, and place the override in the matching location in goradd-project/codegen/templates.

**Comment by vaibhav-kaushal** [comment]
@spekary I have created an org here: https://github.com/goalfw Do you like the name? It starts with 'Go' and is easy to remember. Also, there are no other frameworks right now by that name I think.

**Comment by spekary** [comment]
I am confused. Are you saying you want me to change the name? What is wrong with GoRADD? 

Shannon

> On Apr 17, 2021, at 4:33 AM, Vaibhav Kaushal ***@***.***> wrote:
> 
> 
> @spekary I have created an org here: https://github.com/goalfw Do you like the name? It starts with 'Go' and is easy to remember. Also, there are no other frameworks right now by that name I think.
> 
> —
> You are receiving this because you were mentioned.
> Reply to this email directly, view it on GitHub, or unsubscribe.
> 

Shannon Pekary
***@***.***
