### ISSUE TITLE
Add PostgreSQL as a supported database

### ISSUE THREAD

**Issue by vaibhav-kaushal** [goradd/goradd#173]
Right now goradd can only use MySQL DBs. We should be able to use PostgreSQL databases as well since they are used at a lot of places.

**Comment by spekary** [comment]
Correct. I have a little experience with PostgreSQL. Perhaps we can work on that together. You can see the mysql5.go driver file. We would just need something like that for postgres. Shouldn’t be too difficult.

Shannon

> On Dec 1, 2020, at 11:06 AM, Vaibhav Kaushal <notifications@github.com> wrote:
> 
> 
> Right now goradd can only use MySQL DBs. We should be able to use PostgreSQL databases as well since they are used at a lot of places.
> 
> —
> You are receiving this because you are subscribed to this thread.
> Reply to this email directly, view it on GitHub, or unsubscribe.
> 

Shannon Pekary
spekary@gmail.com

**Comment by vaibhav-kaushal** [comment]
Sure. Will give it a shot.

**Comment by spekary** [comment]
Done
