### ISSUE TITLE
Please check the Quick Start guide

### ISSUE THREAD

**Issue by neuroticimbecile** [goradd/goradd#307]
Good day!
Following the quick start guide, I executed the following:
```
cd
mkdir myproject
cd myproject
```

and then under "**Install GoRadd**", I entered these commands:
```
1.   Execute go install github.com/goradd/goradd@latest
2.    Execute goradd install
```

The first command ran without errors.
The second command returned:

`-bash: goradd: command not found
`

I had to change it to:
`../go/bin/goradd install`

I tried this on:
go version go1.21.1 linux/amd64
running on CentOS 7.9 and Ubuntu 20.04

**Comment by de-shannon** [comment]
Thank you for reporting this. The main issue was this from the Go install instructions:

> The package installs the Go distribution to /usr/local/go. The package should put the /usr/local/go/bin directory in your PATH environment variable. You may need to restart any open Terminal sessions for the change to take effect.


I have updated the installation instructions for goradd to highlight that this is important.

**Comment by neuroticimbecile** [comment]
Thank you for looking into this.
Please let me clarify:

The current directory is **/home/eric/myproject**
This command runs without errors:
`go install github.com/goradd/goradd@latest`
...which means that "**go**" is in my path.

The next command fails:
`goradd install`
Which means that "**goradd**" is not in my path.


Should I also add **/home/eric/go/bin** to the path?
Or is it OK to just execute **goradd** with: 

`../go/bin/goradd install`

or

`/home/eric/go/bin/goradd install`

Thank you

**Comment by de-shannon** [comment]
> Should I also add /home/eric/go/bin to the path?

Yes. That is where the applications you build with the go language will be put by default, and so if you put that in your path, then those applications will be easier to execute.
